<a href="https://colab.research.google.com/github/anillcetin/MachineLearn/blob/main/Hafta2(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
array = np.array([1,9,0,7])
print(array)

[1 9 0 7]


In [ ]:
array2 = np.array([1,2,3,4,5,6,7,8,9,0,3,1,4,6,9])

In [ ]:
print(array2.shape)

(15,)


In [ ]:
a = array2.reshape(3,5)
print(a) #1x15 ten 3x5'e çevirdik

[[1 2 3 4 5]
 [6 7 8 9 0]
 [3 1 4 6 9]]


In [ ]:
print("a dizisinin boyutu: ",a.ndim)

a dizisinin boyutu:  2


In [ ]:
print("a'nın data type'ı : ",a.dtype.name)
print("a'nın boyutu :", a.size )

a'nın data type'ı :  int64
a'nın boyutu : 15


In [ ]:
print("class of a: ", type(a))

class of a:  <class 'numpy.ndarray'>


In [ ]:
zeros = np.zeros((3,4)) #3x4 lük 0 lardan oluşan bir matris yaptık
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
zeros[1,2] = 9 #istediğimiz değeri direkt olarak değiştirebiliriz.
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 9. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones = np.ones((3,4)) #1lerden oluşan 3x4 lük matris
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.empty((3,5))

array([[2.00536740e-316, 0.00000000e+000, 2.00400575e-316,
        5.43472210e-323, 2.00372631e-316],
       [3.36140107e-309, 3.16202013e-322, 3.16202013e-322,
        2.00543064e-316, 2.00351327e-316],
       [2.00239391e-316, 1.97626258e-323, 2.00374251e-316,
        3.36141823e-309, 6.32404027e-322]])

In [ ]:
np.arange(10,50,5) #start point ve end point ile bir range yani mesafe verebiliriz. Sondaki değer ise artış miktari.

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
a = np.linspace(0,10,20) #start,end,dizimizdeki eleman sayısı
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b) #arraylerin her elemanı kendisinin karşısındakini toplanmış hali
print(a-b) #her işlemde mutlaka boyutları eşit olmalı
print(a**b) #a^b şeklinde düşün

[5 7 9]
[-3 -3 -3]
[  1  32 729]


In [ ]:
liste = [1,2,3,4]

array = np.array([5,6,7,8])

print(liste) #listede elemanlar birgül ile ayrılıyor
print(array) #array de ise virgül yok

[1, 2, 3, 4]
[5 6 7 8]


In [ ]:
a = np.array([1,2,3])

b = a
c = a

b[0] = 5

print(a,b,c) #bunu pointer gibi düşün. Aynı adresi tutuyorlar. Bu yüzden hepsinin değeri değişti

[5 2 3] [5 2 3] [5 2 3]


In [ ]:
#eğer kopyalamak istersek bu metodu kullanmamız gerek 
d = a.copy()

print(d)

[1 2 3]


In [ ]:
a = np.array([1,2,3,4,5,6,7])
a[0]
a[0:4]#inclusive,exclusive yani ilk elemandan 3.elemana kadar 


array([1, 2, 3, 4])

In [ ]:
print(a[::-1])

[7 6 5 4 3 2 1]


In [ ]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(b[:,1]) #yani indexi 1.sütunu yazdır
print(b[1,:])#yani indexi 1.satırı yazdır

[2 7]
[ 6  7  8  9 10]


In [ ]:
b[1,1:4]

array([7, 8, 9])

In [ ]:
b[:,-1]

array([ 5, 10])

In [ ]:
b = b.ravel() #tek boyutlu dizi haline getiriyo 
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
b.T #satırı sütun, sütunu satır yapıyor gibi düşünelebilir

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])